# REST API server configuration
server:
  mode: debug # server mode: release, debug, test, 默认为release
  headlthz: true # 开启健康检查
  middleware: # gin中间件: 多个中间件，逗号分隔
  max-ping-count: 10 # 最大ping次数

# MySQL 配置
mysql:
  host: 47.107.127.134:3306 # 数据库地址
  username: remoteAdmin # 数据库用户名
  password: adminpwd # 数据库密码
  database: iam # 数据库名称
  max-idle-connections: 100 # MySQL 最大空闲连接数，默认 100
  max-open-connections: 100 # MySQL 最大打开的连接数，默认 100
  max-connection-life-time: 10s # 空闲连接最大存活时间，默认 10s
  log-level: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info